package gitidx

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClassificationSignals(t *testing.T) {
	cases := []struct {
		path      string
		content   string
		isTracked bool
		isIgnored bool
		wantClass EvidenceClass
	}{
		{
			path:      "src/policy/gcp.go",
			content:   "package policy\nfunc Check() bool { return true }",
			isTracked: true,
			wantClass: EvidenceAuthoritative,
		},
		{
			path:      "out/docker.bundle/vendor/aws-sdk-core/client.go",
			content:   "package client",
			isTracked: true,
			wantClass: EvidenceVendored,
		},
		{
			path:      "out/build_output.o",
			content:   "",
			isTracked: false,
			wantClass: EvidenceBuildArtifact,
		},
		{
			path:      "build/app.bin",
			content:   "",
			isTracked: false,
			wantClass: EvidenceBuildArtifact,
		},
		{
			path:      "pkg/generated/models.go",
			content:   "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage models",
			isTracked: true,
			wantClass: EvidenceGenerated,
		},
		{
			path:      "src/normal_file.go",
			content:   "// Code generated by external tool; DO NOT EDIT.\npackage src",
			isTracked: true,
			wantClass: EvidenceGenerated,
		},
		{
			path:      ".claude/worktrees/agent-1/src/policy.go",
			content:   "package policy",
			isTracked: false,
			wantClass: EvidenceAgentState,
		},
		{
			path:      "src/__pycache__/cache.pyc",
			content:   "",
			isTracked: false,
			wantClass: EvidenceCache,
		},
		{
			path:      "tests/policy_test.go",
			content:   "package tests\nfunc TestPolicy(t *testing.T) {}",
			isTracked: true,
			wantClass: EvidenceTest,
		},
		{
			path:      "fixtures/mock_vpc.json",
			content:   `{"network": "vpc-01"}`,
			isTracked: true,
			wantClass: EvidenceFixture,
		},
		{
			path:      "docs/architecture.md",
			content:   "# Architecture",
			isTracked: true,
			wantClass: EvidenceDocumentation,
		},
	}

	for _, tc := range cases {
		got, _ := Classify(tc.path, []byte(tc.content), tc.isTracked, tc.isIgnored)
		if got != tc.wantClass {
			t.Errorf("Classify(%q) = %q, want %q", tc.path, got, tc.wantClass)
		}
	}
}

func TestAdmissionPolicy_DefaultAndInvariants(t *testing.T) {
	policy := DefaultAdmissionPolicy()

	// Invariant I1: Retrieved(e) => Eligible(e)
	// Known pollution files MUST be ineligible
	polluted := []string{
		"out/docker.bundle/vendor/aws-sdk-core/auth.go",
		"out/docker.bundle/rspec-core/runner.go",
		"vendor/github.com/foo/bar/bar.go",
		"dist/bundle.min.js",
		".claude/worktrees/agent-2/src/main.go",
		"src/__pycache__/compiled.pyc",
	}

	for _, p := range polluted {
		elig := EvaluateAdmission(p, []byte("package test"), true, false, policy)
		if elig.Eligible {
			t.Fatalf("Invariant I1 violated: polluted path %q was admitted as eligible (reason: %s)", p, elig.Reason)
		}
	}

	// Authoritative files MUST be eligible
	clean := []string{
		"plan/policy/provider/gcp/gcp_attach_service_project_policy.go",
		"workflow/hydration/workflow.go",
		"plan/plan.go",
		"workflow/shared/fd_plan.go",
		"plan/policyadd/policyadd.go",
	}
	for _, p := range clean {
		elig := EvaluateAdmission(p, []byte("package test"), true, false, policy)
		if !elig.Eligible {
			t.Fatalf("Authoritative path %q was rejected: %s", p, elig.Reason)
		}
		if elig.Authority != 1.0 {
			t.Fatalf("Expected Authority=1.0 for %q, got %f", p, elig.Authority)
		}
	}

	// Invariant I2: Determinism
	for _, p := range clean {
		e1 := EvaluateAdmission(p, []byte("package test"), true, false, policy)
		e2 := EvaluateAdmission(p, []byte("package test"), true, false, policy)
		if e1.Eligible != e2.Eligible || e1.Authority != e2.Authority || e1.Class != e2.Class {
			t.Fatalf("Invariant I2 violated: non-deterministic admission for %q", p)
		}
	}
}

// R17.5 Benchmark E: Legitimate out/ source explicitly allowed by configuration
func TestAdmissionBenchmarkE_ExplicitAllowOutSource(t *testing.T) {
	defaultPol := DefaultAdmissionPolicy()
	targetPath := "out/important/source.go"
	content := []byte("package important\nfunc Process() {}")

	// Default policy should exclude it as build artifact/out
	eligDefault := EvaluateAdmission(targetPath, content, true, false, defaultPol)
	if eligDefault.Eligible {
		t.Fatalf("Expected %q to be excluded under default policy, got eligible", targetPath)
	}

	// Explicit allow pattern grants admission
	customPolicy := DefaultAdmissionPolicy()
	customPolicy.AllowPatterns = []string{"out/important/**"}

	eligCustom := EvaluateAdmission(targetPath, content, true, false, customPolicy)
	if !eligCustom.Eligible {
		t.Fatalf("Expected %q to be admitted under explicit allow pattern, got rejected: %s", targetPath, eligCustom.Reason)
	}
	if eligCustom.Authority != 1.0 {
		t.Fatalf("Expected promoted Authority=1.0, got %f", eligCustom.Authority)
	}
}

// R17.5 Benchmark F: Generated-but-tracked source
func TestAdmissionBenchmarkF_GeneratedButTracked(t *testing.T) {
	policy := DefaultAdmissionPolicy()
	path := "src/policy/generated_client.go"
	content := []byte("// Code generated by openapi-generator; DO NOT EDIT.\npackage policy")

	elig := EvaluateAdmission(path, content, true, false, policy)
	if elig.Eligible {
		t.Fatalf("Expected generated-but-tracked file %q to be excluded, but was admitted", path)
	}
	if elig.Class != EvidenceGenerated {
		t.Fatalf("Expected class EvidenceGenerated, got %q", elig.Class)
	}
	if !elig.GitTracked {
		t.Fatalf("Expected GitTracked=true")
	}
}

// R17.5 Benchmark A & D: Synthetic fixture with pollution injection & audit manifest
func TestAdmissionSyntheticFixtureAndAudit(t *testing.T) {
	tempDir := t.TempDir()

	files := map[string]string{
		"src/policy.go":                              "package policy\nfunc Check() bool { return true }",
		"src/workflow.go":                            "package workflow\nfunc Run() {}",
		"tests/policy_test.go":                       "package tests\nfunc TestPolicy() {}",
		"fixtures/mock.json":                         `{"mock": true}`,
		"docs/readme.md":                             "# Docs",
		"vendor/fake_gcp_policy.go":                  "package vendor\nfunc Check() bool { return false }",
		"out/docker.bundle/fake_gcp_policy.go":       "package docker\nfunc Check() bool { return false }",
		"out/docker.bundle/vendor/aws.go":            "package aws",
		"build/generated_policy.go":                  "package build",
		"generated/policy.go":                        "package gen",
		".claude/worktrees/agent-1/src/policy.go":    "package policy\nfunc Check() bool { return true }",
	}

	for p, c := range files {
		full := filepath.Join(tempDir, filepath.FromSlash(p))
		_ = os.MkdirAll(filepath.Dir(full), 0755)
		_ = os.WriteFile(full, []byte(c), 0644)
	}

	policy := DefaultAdmissionPolicy()
	admitted, manifest, err := ListEvidenceFiles(tempDir, policy, "test-repo", "head-rev")
	if err != nil {
		t.Fatalf("ListEvidenceFiles failed: %v", err)
	}

	// Admitted files should contain authoritative src, tests, fixtures, and docs,
	// but NO vendor, out, build, generated, or worktrees!
	admittedPaths := make(map[string]bool)
	for _, f := range admitted {
		admittedPaths[f.Path] = true
		if f.Class == EvidenceVendored || f.Class == EvidenceBuildArtifact ||
			f.Class == EvidenceGenerated || f.Class == EvidenceAgentState {
			t.Fatalf("Pollution admitted into evidence: %s (class: %s)", f.Path, f.Class)
		}
	}

	if !admittedPaths["src/policy.go"] || !admittedPaths["src/workflow.go"] {
		t.Fatalf("Missing authoritative source files in admitted set: %+v", admittedPaths)
	}
	if admittedPaths["out/docker.bundle/fake_gcp_policy.go"] || admittedPaths["vendor/fake_gcp_policy.go"] {
		t.Fatalf("Pollution detected in admitted set: %+v", admittedPaths)
	}

	auditText := manifest.FormatAudit()
	if !strings.Contains(auditText, "INDEX AUDIT") {
		t.Fatalf("Audit missing header: %s", auditText)
	}
	if manifest.RejectedCount < 5 {
		t.Fatalf("Expected at least 5 rejected pollution files, got %d", manifest.RejectedCount)
	}
}
