package gitidx

import (
	"bytes"
	"path/filepath"
	"strings"
)

// EvidenceClass defines the authority and provenance category of repository files.
// ContextOS optimizes over valid evidence, not over arbitrary files (R17.5 §5).
type EvidenceClass string

const (
	EvidenceAuthoritative EvidenceClass = "authoritative"
	EvidenceGenerated     EvidenceClass = "generated"
	EvidenceVendored      EvidenceClass = "vendored"
	EvidenceBuildArtifact EvidenceClass = "build_artifact"
	EvidenceCache         EvidenceClass = "cache"
	EvidenceAgentState    EvidenceClass = "agent_state"
	EvidenceTest          EvidenceClass = "test"
	EvidenceFixture       EvidenceClass = "fixture"
	EvidenceDocumentation EvidenceClass = "documentation"
	EvidenceUnknown       EvidenceClass = "unknown"
)

// EvidenceEligibility records the admission decision and authority weighting for an evidence file.
type EvidenceEligibility struct {
	Class         EvidenceClass `json:"class"`
	Eligible      bool          `json:"eligible"`
	Authority     float64       `json:"authority"`
	GitTracked    bool          `json:"git_tracked"`
	GitIgnored    bool          `json:"git_ignored"`
	Generated     bool          `json:"generated"`
	Vendored      bool          `json:"vendored"`
	BuildArtifact bool          `json:"build_artifact"`
	Reason        string        `json:"reason"`
}

// DefaultAuthority returns the baseline authority score for an evidence class.
func DefaultAuthority(c EvidenceClass) float64 {
	switch c {
	case EvidenceAuthoritative:
		return 1.0
	case EvidenceDocumentation:
		return 0.8
	case EvidenceTest:
		return 0.7
	case EvidenceFixture:
		return 0.5
	case EvidenceUnknown:
		return 0.1
	default:
		return 0.0
	}
}

var (
	generatedMarkers = [][]byte{
		[]byte("// Code generated by"),
		[]byte("// Code generated:"),
		[]byte("// DO NOT EDIT"),
		[]byte("// @generated"),
		[]byte("/* @generated"),
		[]byte("# Generated by"),
		[]byte("# @generated"),
		[]byte("/* Autogenerated by"),
		[]byte("<auto-generated"),
		[]byte("Autogenerated by Thrift"),
		[]byte("Generated by the protocol buffer compiler"),
		[]byte("This file was automatically generated"),
	}

	buildArtifactExts = map[string]bool{
		".o":      true,
		".a":      true,
		".so":     true,
		".dylib":  true,
		".exe":    true,
		".bin":    true,
		".class":  true,
		".jar":    true,
		".war":    true,
		".map":    true,
		".min.js": true,
		".min.css": true,
		".pyc":    true,
		".pyo":    true,
		".pyd":    true,
		".bundle": true,
	}
)

// HasGeneratedContentMarkers checks whether the initial chunk of a file contains
// standard auto-generated source headers.
func HasGeneratedContentMarkers(content []byte) bool {
	if len(content) == 0 {
		return false
	}
	head := content
	if len(head) > 4096 {
		head = head[:4096]
	}
	for _, marker := range generatedMarkers {
		if bytes.Contains(head, marker) {
			return true
		}
	}
	return false
}

// IsBuildArtifactPath reports whether the path represents a compiler output, bundle, or binary.
func IsBuildArtifactPath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	ext := filepath.Ext(clean)
	if buildArtifactExts[ext] {
		return true
	}
	if strings.HasSuffix(clean, ".min.js") || strings.HasSuffix(clean, ".min.css") {
		return true
	}

	parts := strings.Split(clean, "/")
	for i, part := range parts {
		if i < len(parts)-1 || ext == "" {
			switch part {
			case "dist", "build", "target", "out", "bin", ".bundle", "docker.bundle":
				return true
			}
		}
	}
	return false
}

// IsVendoredPath reports whether the path represents third-party vendored code.
func IsVendoredPath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		switch part {
		case "vendor", "third_party", "thirdparty", "node_modules", "bower_components":
			return true
		}
	}
	return false
}

// IsAgentStatePath reports whether the path contains agent scratch checkouts or worktrees.
func IsAgentStatePath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	for _, prefix := range AgentWorktreeRoots {
		if strings.HasPrefix(clean, prefix+"/") || clean == prefix {
			return true
		}
	}
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		if part == ".agents" || part == ".contextos" {
			return true
		}
	}
	return false
}

// IsCachePath reports whether the path is a compiler or interpreter cache directory.
func IsCachePath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		switch part {
		case ".cache", "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".turbo":
			return true
		}
	}
	return false
}

// IsTestPath reports whether the file is a unit/integration test.
func IsTestPath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	base := filepath.Base(clean)
	if strings.HasSuffix(base, "_test.go") ||
		strings.HasSuffix(base, "_test.py") ||
		strings.HasPrefix(base, "test_") ||
		strings.HasSuffix(base, ".test.ts") ||
		strings.HasSuffix(base, ".test.js") ||
		strings.HasSuffix(base, ".spec.ts") ||
		strings.HasSuffix(base, ".spec.js") ||
		strings.HasSuffix(base, "test.java") {
		return true
	}
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		if part == "tests" || part == "test" || part == "testing" {
			return true
		}
	}
	return false
}

// IsFixturePath reports whether the file is test fixture data.
func IsFixturePath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		switch part {
		case "fixtures", "fixture", "testdata", "mocks", "mock":
			return true
		}
	}
	return false
}

// IsDocumentationPath reports whether the file is documentation.
func IsDocumentationPath(relSlash string) bool {
	clean := strings.ToLower(filepath.ToSlash(relSlash))
	ext := filepath.Ext(clean)
	switch ext {
	case ".md", ".markdown", ".rst", ".adoc", ".txt":
		return true
	}
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		if part == "docs" || part == "doc" || part == "documentation" {
			return true
		}
	}
	return false
}

// Classify inspects path, file extensions, and optional content headers to assign an EvidenceClass.
// Note: Git tracking status alone does NOT imply authority (R17.5 §7).
func Classify(relPath string, content []byte, isTracked bool, isIgnored bool) (EvidenceClass, string) {
	relSlash := filepath.ToSlash(relPath)

	if IsAgentStatePath(relSlash) {
		return EvidenceAgentState, "agent worktree or internal state path"
	}
	if IsCachePath(relSlash) {
		return EvidenceCache, "cache directory"
	}
	if IsVendoredPath(relSlash) {
		return EvidenceVendored, "third-party or vendored dependency"
	}
	if IsBuildArtifactPath(relSlash) {
		return EvidenceBuildArtifact, "build output or compiler artifact"
	}
	if HasGeneratedContentMarkers(content) {
		return EvidenceGenerated, "content header indicates generated code"
	}

	clean := strings.ToLower(relSlash)
	parts := strings.Split(clean, "/")
	for _, part := range parts {
		if part == "generated" || part == ".gen" || part == "gen" {
			return EvidenceGenerated, "generated path marker"
		}
	}

	if IsFixturePath(relSlash) {
		return EvidenceFixture, "test fixture or mock data"
	}
	if IsTestPath(relSlash) {
		return EvidenceTest, "automated test suite"
	}
	if IsDocumentationPath(relSlash) {
		return EvidenceDocumentation, "project documentation"
	}

	ext := filepath.Ext(relSlash)
	if Supported(relSlash) || ext == ".json" || ext == ".yaml" || ext == ".yml" || ext == ".toml" {
		return EvidenceAuthoritative, "authoritative project source or configuration"
	}

	return EvidenceUnknown, "unrecognized file format or category"
}
